spring.application.name=LetsSplitIt
spring.data.mongodb.uri=mongodb+srv://veed2023_db_user:z4DQK3rycZMIAEEL@testdb.r7ljldx.mongodb.net/LetsSplitIt?retryWrites=true&w=majority

jwt.secret=TGV0c1NwbGl0SXRTZWNyZXRGb3JKd3RUb2tlbkF1dGg=
jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:3000
